export const ActionTyeps = {
    ADMIN_LOGGING_IN: 'ADMIN_LOGGING_IN',
    ADMIN_CHECK_LOGIN: 'ADMIN_CHECK_LOGIN',
    ADMIN_LOGOUT: 'ADMIN_LOGOUT',
    ADMIN_FORGOT_PASSWORD: 'ADMIN_FORGOT_PASSWORD'
};