export const ActionTypes = {
    PAGE_LOADING: 'PAGE_LOADING',
	ADMIN_SIDE_MENU_STATE: 'ADMIN_SIDE_MENU_STATE',
    ADMIN_LOGGING_IN: 'ADMIN_LOGGING_IN',
    ADMIN_CHECK_LOGIN: 'ADMIN_CHECK_LOGIN',
    ADMIN_LOGOUT: 'ADMIN_LOGOUT',
    ADMIN_FORGOT_PASSWORD: 'ADMIN_FORGOT_PASSWORD'
};